#!/usr/bin/env python
"""Submit jobs to a SLURM queue to generate predictions for a dataset using
avocado.

This requires that avocado be installed and that the avocado_predict script
is on the PATH.

Adapted from avocado_predict_submit (SGE) and avocado_featurize_submit (SLURM).
"""

import argparse
import os
import subprocess

import avocado

slurm_template = """#!/bin/bash
#SBATCH --export=ALL
#SBATCH -J {job_name}
#SBATCH -o {jobs_directory}/{job_name}.out
#SBATCH -e {jobs_directory}/{job_name}.err

# Use a single core for each job. This parallelizes better than trying to use
# multiple cores per job.
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_NUM_THREADS=1

cd {working_directory}
avocado_predict \\
    {dataset} \\
    {classifier} \\
    --chunk {job} \\
    --num_chunks {num_chunks} \\
"""

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        'dataset',
        help='Name of the dataset to generate predictions for.'
    )
    parser.add_argument(
        'classifier',
        help='Name of the classifier to use.'
    )
    parser.add_argument(
        '--num_chunks',
        type=int,
        default=50,
        help='Total number of chunks the dataset is split into. '
        '(default: %(default)s)',
    )
    parser.add_argument(
        '--chunks',
        type=int,
        nargs='+',
        default=None,
        help='Specific chunk indices to submit (e.g. --chunks 0 1 2 3 4). '
        'If not set, all chunks are submitted.'
    )
    parser.add_argument(
        '--working_directory',
        default=None,
        help='Working directory. Default is the current directory.'
    )
    parser.add_argument(
        '--jobs_directory',
        default=None,
        help='Jobs directory for sbatch scripts and output. Default is '
        '"[working_directory]/jobs/predict_[dataset]/"'
    )
    parser.add_argument(
        '--extra_arguments',
        default='',
        help='Additional arguments to pass to sbatch'
    )

    raw_args = parser.parse_args()

    # Build a dictionary with the arguments that will be used to format the
    # submit script.
    args = vars(raw_args).copy()

    # Update the working directory if it wasn't set.
    if args['working_directory'] is None:
        args['working_directory'] = os.getcwd()

    # Update the log directory if it wasn't set and make sure that it exists.
    if args['jobs_directory'] is None:
        args['jobs_directory'] = os.path.join(
            args['working_directory'], 'jobs',
            'predict_%s_%s' % (args['dataset'], args['classifier'])
        )
    os.makedirs(args['jobs_directory'], exist_ok=True)

    # Determine which chunks to submit
    if args['chunks'] is not None:
        chunk_list = args['chunks']
    else:
        chunk_list = list(range(args['num_chunks']))

    # Create and submit the jobs one by one
    for job_id in chunk_list:
        job_args = args.copy()

        job_args['job'] = job_id

        job_name = 'predict_%04d_%s_%s' % (job_id, args['dataset'],
                                           args['classifier'])
        job_args['job_name'] = job_name

        job_path = '{jobs_directory}/{job_name}.sh'.format(**job_args)

        job_template = slurm_template.format(**job_args)

        # Write the jobs file
        with open(job_path, 'w') as job_file:
            job_file.write(job_template)

        # Submit the job
        subprocess.call(["sbatch"] + args['extra_arguments'].split() +
                        [job_path])
